"""VO beats for How to Buy a Piper M350 (Ep4, N333WR). Story cut: title -> choose -> shortlist -> the one we ran -> report sections as questions -> offer -> keep watching -> verdict. Numbers as words, no ellipses."""
BEATS = [
("b01", "title", "This is How to Buy a Piper M three fifty. One real airplane that is for sale right now, one real NextPlane report, and the questions a smart buyer asks, in the order the data answers them."),
("b02", "problem", "Step one. Choose which one. The M three fifty is the only pressurized piston single in production today. It replaced the Malibu Mirage in twenty fifteen, on the same airframe. This week NextPlane is tracking thirty-two Mirages and M three fifties for sale in the U S. Twenty-seven of them show a price."),
("b03", "ladder", "The first question is which era, because the era sets the price band. Mirages from nineteen eighty-nine through two thousand two ask around five hundred fifty thousand dollars. The later Mirages, twenty eleven to twenty fourteen, sit near eight hundred twenty-four thousand. Early M three fifties ask about one point one seven five million. The twenty twenty-two and twenty twenty-three airplanes ask just under one and a half million. And the nearly new ones sit near one point nine five million. So a late-model used airplane is priced close to new, with someone else's hours on it."),
("b04", "shortlist", "Now narrow it down the way a buyer would. M three fifties with a published price: nine. Take out the four that are new or nearly new, and the one from twenty fifteen. That leaves four. A twenty nineteen, a twenty twenty, a twenty twenty-two, and a twenty twenty-three, more than three hundred thousand dollars apart for the same model. So we run the one in the middle of that gap."),
("b05", "pick", "This one. A twenty twenty-two M three fifty, listed by a dealer in Kansas, asking one million, four hundred seventy-five thousand dollars. Here is what stopped us. The report puts a standard-equipped M three fifty at about one point two nine million dollars, new, in twenty twenty-two. Four years and six hundred eighty-eight hours later, this one is asking fourteen percent more than that. And while it has been for sale, it has kept flying. So let's follow the data."),
("b06", "header", "Step two. Evaluate the one. Open the NextPlane Aircraft Report and start with the headline. No N T S B damage or accident record. No security agreement indexed against the airframe. But one line is flagged. The current owner has held this airplane for ten months, and the report's note is simple: short holds are worth a question. We will come back to that. First, is the price fair?"),
("b07", "value", "NextPlane's estimate, built from comparable M three fifties from model years twenty nineteen to twenty twenty-five, is one million, two hundred ninety-six thousand, five hundred dollars. The middle half of those comparables runs from about one point two million to one point five nine million. So the ask sits inside the range, but one hundred seventy-eight thousand dollars above the estimate. About fourteen percent."),
("b08", "comps", "Here are the closest ones. A twenty twenty-one with seven hundred hours was last listed at one million, two hundred ninety-eight thousand. A twenty twenty with five hundred forty-seven hours, at one point two nine five million. Both left the market in the last few weeks. Above ours, a twenty twenty-three with just two hundred thirty hours asks one million, four hundred ninety-nine thousand, nine hundred. So ours is priced twenty-five thousand under an airplane a year newer with a third of the hours. What could justify that? The listing says every twenty twenty-three option is installed. And then there is the engine."),
("b09", "engine", "The engine is the surprise. The listing shows six hundred eighty-eight hours on the airframe, but only four hundred forty-four on the engine. On a four-year-old airplane, those numbers normally match. A younger engine is good news. The report puts this airplane at one dollar sixty per nautical mile, against one dollar sixty-seven for the average one for sale, because this engine has about three hundred more hours of life left. That is worth about thirteen and a half thousand dollars. But it is also a question. Why is the engine younger than the airframe? Ask, and read the engine logbook."),
("b10", "newprice", "So why would anyone pay more than new for a used airplane? Because new moved. The report tracks what a new M three fifty costs each year. About one point two nine million, standard equipped, in twenty twenty-two. About two point zero six million in twenty twenty-five. When the replacement costs sixty percent more, used prices follow it up. That explains the market. It does not explain this airplane's premium over its neighbors."),
("b11", "pricehist", "Has the seller moved? Twice. Listed in June at one million, five hundred fifty thousand dollars. Twenty-five thousand off in July. Fifty thousand more in August. Seventy-five thousand in total, four point eight percent. Among comparable listings from this spring and early summer, ten of twenty-four have cut, and the typical total cut was under three percent. So this seller has already moved more than most. But nothing has changed since August twenty-first."),
("b12", "owner", "Now back to that flag. The F A A registry shows a Georgia company, with a certificate issued in December twenty twenty-five. The airplane was listed for sale in June, six months later. A short hold is not a red flag by itself. Plans change. But it is a fair question for the broker. Why is it for sale so soon?"),
("b13", "flight", "And is it still flying? Very much. NextPlane's A D S B tracking shows three hundred seventy-two hours in the last twelve months, nearly all of it since November. Sixty-one of those hours came in the last three months, while the airplane has been on the market. So the six hundred eighty-eight hours in the listing may already be out of date. Ask for the current airframe and engine times in writing."),
("b14", "ads", "What should the paperwork show? The report matches five active airworthiness directives to this airplane, three of them conditional on installed parts. On a twenty twenty-two airframe, that is a short list. The listing shows the annual as April twenty twenty-six. Ask whether that is when it was done, or when it was due. The logbooks will tell you."),
("b15", "sdr", "Has it ever been hurt? The listing reports no damage history. NextPlane finds no N T S B record, and no service difficulty report filed under this N number. Clean on paper. Your pre-buy inspector confirms it in metal."),
("b16", "opcost", "What will it cost to keep? The report's estimate, at one hundred twenty hours a year, is fifty-one thousand, seven hundred fifty-nine dollars. Four hundred thirty-one dollars an hour. The biggest line is not fuel. It is insurance, at about twenty thousand dollars a year. Get your own quote before you make an offer."),
("b17", "seller", "And who am I dealing with? A dealer, not the owner. All fifteen airplanes this dealer lists today come from the same P A forty-six family. A specialist knows what the airplane is worth. So come with numbers."),
("b18", "offer", "Step three. Price the offer. Start with NextPlane's estimate. One million, two hundred ninety-six thousand, five hundred. Add the engine, about thirteen and a half thousand. That lands near one point three one million, right where the closest airplanes were last listed. And the timing favors the buyer. This one has been listed for more than one hundred fifteen days, and NextPlane's model gives it about an even chance of another price cut in the next ninety. So a reasonable opening is around one point three one million, backed by the comps, not by a lowball. Make it subject to current hours in writing, the engine logbook, and a pre-buy at a shop you choose."),
("b19", "watch", "Step four. Keep watching. If this is not your airplane, keep the other three on your list. In the last two weeks, six Mirages and M three fifties were newly listed, and sellers made four price cuts."),
("b20", "verdict", "So who is this airplane right for? A buyer who wants a late-model M three fifty with a young engine and every option, without paying two million dollars for a new one. If you are shopping on price, the twenty nineteen and twenty twenty airplanes ask almost three hundred thousand less. Priced above the estimate. Clean history. And three questions before you call it a deal. Why so soon, why the younger engine, and what are the hours today?"),
("b21", "end", "Before you call the broker, check the data at NextPlane dot U S."),
]
if __name__ == "__main__":
    n = sum(len(t.split()) for _, _, t in BEATS); print("words", n)
    assert not any("..." in t for _, _, t in BEATS)
